version: "3.9"
services:
  test-db:
    container_name: test-db
    image: "postgres:14"
    ports:
      - "5433:5432"
    environment:
      - "POSTGRES_USER=user"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=db"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql